const PAYMENT_STATUS_MAP = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
  REFUNDED: 'REFUNDED',
  DECLINED: 'DECLINED',
};

const INTENT_STATUSES = [PAYMENT_STATUS_MAP.INACTIVE, PAYMENT_STATUS_MAP.ACTIVE];

export { PAYMENT_STATUS_MAP, INTENT_STATUSES };
